### ISSUE TITLE
多页，页面之间的跳转怎么搞得

### ISSUE THREAD

**Issue by anfeng1** [crli/vue-cli-multipage#1]
你这个多页是有多个单页构成的吧，如果想要从一个单页的某个状态调到另外一个单页的某个状态，怎么实现的

**Comment by fantasy525** [comment]
+1，多页之间跳转页面，没有vue-router了怎么传值？用传统的location.href?加参数？另外多页如果需要判断登录权限怎么处理？没登录的话不让看到某些页面，防止用户直接输入网址查看，是需要后台配合去拦截请求还是我们在每个页面的钩子里面自己去判断？

**Comment by crli** [comment]
多页之间跳转使用location.href＋参数，如果业务逻辑每个页面都是一个单页面，那只能后台配合，如果各别单页内有相应逻辑，就是有vue-router，可以用钩子，或者后台，或者两种一起。如果有用到vuex状态管理，状态管理不能各单页之间传递，只能在单页面内的个路由组件间共享
