### ISSUE TITLE
大佬， 涉及到VueI18n国际化的问题

### ISSUE THREAD

**Issue by SongChao1123** [crli/vue-cli-multipage#2]
因为项目需要16种语言支持，但是发现使用了Vue.use(VueI18n);后会打包在dist目录中同一个JS文件里，请问下VueI18n如何才能分离出来打包呢

**Comment by crli** [comment]
这个脚手架其实已经做好了分离打包的功能，所以会进入同一个js文件，如果您只想分离打包VueI18n，可以将VueI18n相关依赖文件放在一个js内，然后在需要时候引入，同时配置webpack.base.conf.js的entry相关，以及webpack.prod.conf.js内html-webpack-plugin相关，与公共组件components分离打包一个思路，您可以尝试下

**Comment by SongChao1123** [comment]
好的  多谢大佬， 我尝试一下
